package guicomecocos;

import java.awt.Color;
import javax.swing.JColorChooser;

public class ConfiguracionTemaDialog extends javax.swing.JDialog {
    ComecocosFrame frame;

    /** Creates new form ConfiguracionTemaDialog */
    public ConfiguracionTemaDialog(ComecocosFrame cf) {
        super(cf, true);
        this.frame = cf;
        initComponents();
        this.panel_color_borde.setBackground(frame.cgui.getColorBorde());
        this.panel_color_fondo.setBackground(frame.cgui.getColorFondo());
        this.panel_color_puntos.setBackground(frame.cgui.getColorPunto());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cModos = new javax.swing.JComboBox();
        bCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        button_fondo = new javax.swing.JButton();
        button_borde = new javax.swing.JButton();
        button_puntos = new javax.swing.JButton();
        panel_color_fondo = new javax.swing.JPanel();
        panel_color_borde = new javax.swing.JPanel();
        panel_color_puntos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("Modos:");

        cModos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arcade", "Monstruo de las Galletas", "Chiquito", "Super Mario" }));
        cModos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cModosActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Colores"));

        button_fondo.setText("Fondo");
        button_fondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_fondoActionPerformed(evt);
            }
        });

        button_borde.setText("Borde");
        button_borde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bordeActionPerformed(evt);
            }
        });

        button_puntos.setText("Puntos");
        button_puntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_puntosActionPerformed(evt);
            }
        });

        panel_color_fondo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panel_color_fondoLayout = new javax.swing.GroupLayout(panel_color_fondo);
        panel_color_fondo.setLayout(panel_color_fondoLayout);
        panel_color_fondoLayout.setHorizontalGroup(
            panel_color_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        panel_color_fondoLayout.setVerticalGroup(
            panel_color_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        panel_color_borde.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panel_color_bordeLayout = new javax.swing.GroupLayout(panel_color_borde);
        panel_color_borde.setLayout(panel_color_bordeLayout);
        panel_color_bordeLayout.setHorizontalGroup(
            panel_color_bordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        panel_color_bordeLayout.setVerticalGroup(
            panel_color_bordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        panel_color_puntos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panel_color_puntosLayout = new javax.swing.GroupLayout(panel_color_puntos);
        panel_color_puntos.setLayout(panel_color_puntosLayout);
        panel_color_puntosLayout.setHorizontalGroup(
            panel_color_puntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        panel_color_puntosLayout.setVerticalGroup(
            panel_color_puntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_puntos, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(button_borde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_color_fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_color_puntos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_color_borde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_color_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_borde)
                    .addComponent(panel_color_borde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel_color_puntos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_puntos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cModos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cModos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        frame.cgui.cambiarTema(cModos.getSelectedIndex());
        ((PanelMapa) frame.getPanel()).recargarImagenes();
        dispose();
    }//GEN-LAST:event_bAceptarActionPerformed

    private void cModosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cModosActionPerformed

}//GEN-LAST:event_cModosActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        dispose();
}//GEN-LAST:event_bCancelarActionPerformed

    private void button_fondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_fondoActionPerformed
        Color actual = frame.cgui.getColorFondo();
        Color nuevo = JColorChooser.showDialog(this, "Elija un color de fondo", actual);
        if (nuevo != null) {
            frame.cgui.setColorFondo(nuevo);
            this.panel_color_fondo.setBackground(nuevo);
        }
}//GEN-LAST:event_button_fondoActionPerformed

    private void button_bordeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bordeActionPerformed
        Color actual = frame.cgui.getColorBorde();
        Color nuevo = JColorChooser.showDialog(this, "Elija un color de borde", actual);
        if (nuevo != null) {
            frame.cgui.setColorBorde(nuevo);
            this.panel_color_borde.setBackground(nuevo);
        }
}//GEN-LAST:event_button_bordeActionPerformed

    private void button_puntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_puntosActionPerformed
        Color actual = frame.cgui.getColorPunto();
        Color nuevo = JColorChooser.showDialog(this, "Elija color de los puntos", actual);
        if (nuevo != null) {
            frame.cgui.setColorPunto(nuevo);
            this.panel_color_puntos.setBackground(nuevo);
        }
}//GEN-LAST:event_button_puntosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton button_borde;
    private javax.swing.JButton button_fondo;
    private javax.swing.JButton button_puntos;
    private javax.swing.JComboBox cModos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_color_borde;
    private javax.swing.JPanel panel_color_fondo;
    private javax.swing.JPanel panel_color_puntos;
    // End of variables declaration//GEN-END:variables

}
